### ISSUE TITLE
Work on placement of everything on the page

### ISSUE THREAD

**Issue by petemaynard** [KDeLaria/bartending-school#40]
Currently everything on the page is in one container and on one row.

Should have:
Row One:
  Column 1: 
       - "Bartender School" text at top
       - Instructions button and Drink button on the bottom, with Instructions to the left and Drink on the right, perhaps centered in the column
  Column 2: carousel

Row Two:
   Column 1:
      - Placeholder images of bottles, glasses, ice, bar tools displayed until user slicks Drink button (optional)
      - Checkboxes in three columns of five ingredients
    Column 2:
      - Captioned picture of the drink 

Row Three:
     Column 1:
        - Three cards with the bar positions
     Column 2:
        - List of five mistake drinks with links to open second page
 
Row Four:
      Let's give ourselves some credits at the bottom.  And maybe a link to some drinking problem website.

**Comment by RB2277** [comment]
Completed in several different merges
